export const navConfig = [
  { title: "Home", path: "/" },
  { title: "Services", path: "/services" },
  {
    title: "Insights",
    path: "/insights",
  },
  { title: "Careers", path: "/careers" },
];

export const pageLinks = [
  {
    order: "1",
    subheader: "Clients",
    cover: "/assets/images/menu/menu_marketing.jpg",
    items: [
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
    ],
  },
  {
    order: "6",
    subheader: "Services",
    cover: "/assets/images/menu/menu_travel.jpg",
    items: [
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
    ],
  },
  {
    order: "2",
    subheader: "Industries",
    cover: "/assets/images/menu/menu_career.jpg",
    items: [
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
    ],
  },
  {
    order: "5",
    subheader: "Other",
    cover: "/assets/images/menu/menu_elearning.jpg",
    items: [
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
    ],
  },
  {
    isNew: true,
    order: "3",
    subheader: "Other",
    cover: "/assets/images/menu/menu_ecommerce.jpg",
    items: [
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
    ],
  },
  {
    order: "4",
    subheader: "Other",
    items: [
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
      { title: "Subtitle", path: "/" },
    ],
  },
];
