export const _id = [...Array(40)].map(
  (_, index) => `e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index + 1}`,
);

export const _descriptions = [
  "An in-depth look into Stark Law, its objectives, and its implications for healthcare providers.",
  "Unveiling the methodologies and best practices in determining the fair market value within the healthcare sector.",
  "Practical strategies for healthcare institutions to avoid violations and maintain compliance with Anti-Kickback regulations.",
  "Exploring the intricate relationship between asset valuation in healthcare and the mandates set by Stark Law.",
  "Debunking prevalent misconceptions surrounding Anti-Kickback regulations and shedding light on actual stipulations.",
  "Expert perspectives on the intricacies and challenges faced during healthcare asset valuations.",
  "A step-by-step guide for healthcare entities to ensure consistent compliance with Stark Law regulations.",
  "Highlighting the most common oversights and errors in healthcare asset valuations and how to avoid them.",
  "A deep dive into how healthcare consultants can guide organizations in maintaining Anti-Kickback compliance.",
  "A real-world example of navigating through the maze of Stark Law and emerging compliant and successful.",
  "Drawing distinctions between Stark Law and Anti-Kickback regulations, and understanding their unique challenges.",
  "Discover the cutting-edge tools and tech solutions that are setting new standards in fair market value determinations.",
  "Discussing the evolving nature of healthcare and the escalating importance of accurate asset valuation.",
  "Understanding the broader strategic advantages of staying compliant with Stark Law and Anti-Kickback regulations beyond just avoiding penalties.",
  "Handy recommendations for healthcare providers to remain updated and ahead of regulatory shifts.",
  "Peeling back the layers of the valuation process to understand how experts determine the fair market value in healthcare.",
  "Diving into the business side of healthcare, emphasizing risk management against Stark Law and Anti-Kickback pitfalls.",
  "An overview of the all-encompassing approach, from initial due diligence to ensuring ongoing compliance in healthcare valuation.",
  "Expert insights addressing the often ambiguous areas in Stark Law and Anti-Kickback interpretations and compliance.",
  "Predicting the trajectory of healthcare valuation, including upcoming trends and shifts over the next decade.",
];

export const _tags = [
  "Technology",
  "Marketing",
  "Design",
  "Photography",
  "Art",
  "Fashion",
  "Food",
  "Travel",
  "Fitness",
  "Nature",
  "Business",
  "Music",
  "Health",
  "Books",
  "Sports",
  "Film",
  "Education",
  "Motivation",
  "Gaming",
  "Pets",
  "Cooking",
  "Finance",
  "Selfcare",
  "Writing",
];

export const _insightTitles = [
  "Understanding Stark Law: A Comprehensive Guide",
  "Determining Fair Market Value in Healthcare: Best Practices",
  "Avoiding Anti-Kickback Violations: Key Strategies for Healthcare Providers",
  "The Intersection of Stark Law and Fair Market Valuation",
  "5 Common Misconceptions about Anti-Kickback Regulations",
  "Challenges in Healthcare Asset Valuation: Expert Insights",
  "Ensuring Compliance: Navigating the Complexities of Stark Law",
  "Top 10 Mistakes in Healthcare Asset Valuation",
  "The Role of a Healthcare Consultant in Ensuring Anti-Kickback Compliance",
  "Case Study: Successfully Navigating Stark Law Challenges",
  "Key Differences Between Stark Law and Anti-Kickback Regulations",
  "In-depth: Tools and Technologies for Fair Market Value Assessment",
  "Evolving Healthcare Landscape: The Growing Importance of Fair Market Valuation",
  "Beyond Compliance: Strategic Benefits of Understanding Stark Law and Anti-Kickback Regulations",
  "Practical Tips for Healthcare Organizations to Stay Ahead of Regulatory Changes",
  "Demystifying the Process: How We Determine Fair Market Value",
  "The Business of Healthcare: Risk Management in the Face of Stark Law and Anti-Kickback Statute",
  "From Due Diligence to Compliance: A Holistic Approach to Healthcare Valuation",
  "Addressing Grey Areas: Expert Q&A on Stark Law and Anti-Kickback Challenges",
  "The Future of Healthcare Valuation: Trends to Watch in the Next Decade",
];

export const _booleans = [
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  false,
  false,
  false,
  true,
  true,
  true,
  false,
  false,
  false,
  true,
  false,
  false,
  false,
  true,
  false,
  false,
  true,
];

export const _fullNames = [
  "Jayvion Simon",
  "Lucian Obrien",
  "Deja Brady",
  "Harrison Stein",
  "Reece Chung",
  "Lainey Davidson",
  "Cristopher Cardenas",
  "Melanie Noble",
  "Chase Day",
  "Shawn Manning",
  "Soren Durham",
  "Cortez Herring",
  "Brycen Jimenez",
  "Giana Brandt",
  "Aspen Schmitt",
  "Colten Aguilar",
  "Angelique Morse",
  "Selina Boyer",
  "Lawson Bass",
  "Ariana Lang",
  "Amiah Pruitt",
  "Harold Mcgrath",
  "Esperanza Mcintyre",
  "Mireya Conner",
];

export const _roles = [
  "HR Manager",
  "Data Analyst",
  "Legal Counsel",
  "UX/UI Designer",
  "Project Manager",
  "Account Manager",
  "Registered Nurse",
  "Business Analyst",
  "Creative Director",
  "Financial Planner",
  "Event Coordinator",
  "Marketing Director",
  "Software Developer",
  "Research Scientist",
  "Content Strategist",
  "Operations Manager",
  "Sales Representative",
  "Supply Chain Analyst",
  "Operations Coordinator",
  "Customer Service Associate",
  "Quality Assurance Specialist",
  "CEO",
  "CFO",
  "CTO",
];
